name: Build, test and publish
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'scripts/**'

jobs:
  test-scripts-with-local-packages:
    name: Test scripts with local packages
    uses: ./.github/workflows/test-workload.yml
    with:
      template: uno
      path: src/workload/Uno.Sdk.Build
      source: artifacts/nuget

  publish:
    needs: test-scripts-with-local-packages
    name: Publish NuGet packages
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build packages"
        run: dotnet build
          src/workload/Uno.Sdk.Build
          --configuration Release

      - name: "Publish"
        run: dotnet nuget push
          **.nupkg
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
          --api-key ${{ secrets.NUGET_KEY }}
      
  wait-nuget:
    name: Wait NuGet packages
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash
        
  test-scripts-with-nuget-packages:
    name: Test scripts with NuGet packages
    needs: wait-nuget
    uses: ./.github/workflows/test-workload.yml
    with:
      template: uno
  
  build-test-publish-uno:
    name: Uno WinUI meta package
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path: src/libs/Uno
      workloads: maui
      generate-build-number: false
      conventional-commits-publish-conditions: false
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
      
  build-test-publish-uno-uwp:
    name: Uno UWP meta package
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path: src/libs/Uno.Uwp
      workloads: maui
      generate-build-number: false
      conventional-commits-publish-conditions: false
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}