name: Build, test and publish
on:
  push:
    branches:
      - main

jobs:
  test-scripts-with-local-packages:
    name: Test scripts with local packages
    uses: ./.github/workflows/test-workload.yml
    with:
      template: uno
      path: src/workload/Uno.Sdk.Manifest
      source: artifacts/nuget

  publish:
    needs: test-scripts-with-local-packages
    name: Publish NuGet packages
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build packages"
        run: dotnet build
          src/workload/Uno.Sdk.Manifest
          --configuration Release

      - name: "Publish"
        run: dotnet nuget push
          **.nupkg
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
          --api-key ${{ secrets.NUGET_KEY }}
      
  wait-nuget:
    name: Wait NuGet packages
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash
        
  test-scripts-with-nuget-packages:
    name: Test scripts with NuGet packages
    needs: wait-nuget
    uses: ./.github/workflows/test-workload.yml
    with:
      template: uno