name: Build and test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'scripts/**'

jobs:
  test-scripts-with-local-packages:
    name: Test scripts with local packages
    uses: ./.github/workflows/test-workload.yml
    with:
      template: uno
      path: src/workload/Uno.Sdk.Build
      source: artifacts/nuget